In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

data = pd.read_csv('survey_results_public2021.csv') #changed the source
data_lastyear = pd.read_csv('survey_results_public2020.csv')
pd.set_option('display.max_columns', 100) # displays enough columns
# for working with salaries the problem is that total money and purchasing power are different? f.e compare India and US
# focus on US/EU?
#gender/race pay gap present in developer industry? if so, did it get better over time?
#difference in behaviour if NEWStuck depending on gender, age, education?

In [2]:
data.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'Country', 'US_State',
       'UK_Country', 'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode',
       'YearsCodePro', 'DevType', 'OrgSize', 'Currency', 'CompTotal',
       'CompFreq', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [3]:
data.filter(['MainBranch', 'Employment','Country', 'EdLevel', 'Age1stCode', 'YearsCode', 'YearsCodePro', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'NEWStuck', 'Age', 'Gender', 'Ethnicity', 'MentalHealth', 'ConvertedCompYearly' ])

,MainBranch,Employment,Country,EdLevel,Age1stCode,YearsCode,YearsCodePro,LanguageHaveWorkedWith,LanguageWantToWorkWith,NEWStuck,Age,Gender,Ethnicity,MentalHealth,ConvertedCompYearly
0,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,"Secondary school (e.g. American high school, G...",18 - 24 years,NaN,NaN,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,Call a coworker or friend;Visit Stack Overflow...,25-34 years old,Man,White or of European descent,None of the above,62268.0
1,I am a student who is learning to code,"Student, full-time",Netherlands,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,7,NaN,JavaScript;Python,NaN,Visit Stack Overflow;Google it,18-24 years old,Man,White or of European descent,None of the above,NaN
2,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,Visit Stack Overflow;Google it;Watch help / tu...,18-24 years old,Man,Prefer not to say,None of the above,NaN
3,I am a developer by profession,Employed full-time,Austria,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,JavaScript;TypeScript,JavaScript;TypeScript,Call a coworker or friend;Visit Stack Overflow...,35-44 years old,Man,White or of European descent,NaN,NaN
4,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,17,10,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Visit Stack Overflow;Go for a walk or other ph...,25-34 years old,Man,White or of European descent,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,I am a developer by profession,Employed full-time,United States of America,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,6,5,Clojure;Kotlin;SQL,Clojure,Call a coworker or friend;Google it,25-34 years old,Man,White or of European descent,I have a concentration and/or memory disorder ...,160500.0
83435,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,4,2,NaN,NaN,Call a coworker or friend;Visit Stack Overflow...,18-24 years old,Man,Black or of African descent,None of the above,3960.0
83436,I am a developer by profession,Employed full-time,United States of America,"Secondary school (e.g. American high school, G...",11 - 17 years,10,4,Groovy;Java;Python,Java;Python,Call a coworker or friend;Visit Stack Overflow...,25-34 years old,Man,White or of European descent,None of the above,90000.0
83437,I am a developer by profession,Employed full-time,Canada,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,5,3,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Call a coworker or friend;Visit Stack Overflow...,25-34 years old,Man,White or of European descent,I have a mood or emotional disorder (e.g. depr...,816816.0
83438,I am a developer by profession,Employed full-time,Brazil,"Professional degree (JD, MD, etc.)",11 - 17 years,14,4,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Call a coworker or friend;Visit Stack Overflow...,18-24 years old,Man,Hispanic or Latino/a/x,None of the above,21168.0

In [ ]:
data['LanguageHaveWorkedWith'].str.contains('C++').sum()

In [ ]:
grouped_Country = data.groupby(['Country'])

In [6]:
#without C++! why does this not work with C++? see cell above
languages_Answers = ['Clojure', 'Dart', 'Java', 'Perl', 'APL', 'Node.js', 'LISP', 'Kotlin', 'Go', 'Scala', 'Crystal', 'HTML/CSS', 'Groovy', 'COBOL', 'Bash/Shell', 'Erlang', 'Delphi', 'C', 'F#', 'JavaScript', 'Swift', 'Elixir', 'PHP', 'TypeScript', 'Rust', 'SQL', 'Matlab', 'Julia', 'Python', 'Assembly', 'C#', 'VBA', 'Haskell', 'Objective-C', 'R', 'Ruby', 'PowerShell']

In [ ]:
country_answers = data['Country'].value_counts()
country_uses_lang = grouped_Country['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Java').sum())

In [ ]:
df = pd.concat([country_answers, country_uses_lang], axis = 'columns', sort = False)

In [ ]:
df.rename(columns={'Country': 'Respondents', 'LanguageHaveWorkedWith': 'Python'}, inplace= True)

In [8]:
grouped_Country = data.groupby(['Country'])
df = data['Country'].value_counts()
df.rename({'Country': 'Respondents'}, inplace= True)
for str in languages_Answers:
    temp = grouped_Country['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains(str).sum())
    df = pd.concat([df,temp], axis = 'columns', sort = False)
    df.rename(columns={'LanguageHaveWorkedWith': str}, inplace= True)

In [9]:
df

,Country,Clojure,Dart,Java,Perl,APL,Node.js,LISP,Kotlin,Go,Scala,Crystal,HTML/CSS,Groovy,COBOL,Bash/Shell,Erlang,Delphi,C,F#,JavaScript,Swift,Elixir,PHP,TypeScript,Rust,SQL,Matlab,Julia,Python,Assembly,C#,VBA,Haskell,Objective-C,R,Ruby,PowerShell
United States of America,15288,477,419,11321,602,112,5321,345,982,1898,442,135,8492,567,82,5757,161,152,12016,197,9987,919,399,2152,4701,1584,7332,571,282,7975,916,4497,719,368,479,3707,1646,2252
India,10511,50,961,7987,142,43,3373,58,838,636,203,24,5844,199,48,1483,30,21,7696,15,6460,391,55,2044,2339,252,4289,529,81,5233,379,1632,301,62,278,974,311,593
Germany,5625,114,297,4147,166,25,1787,78,605,614,163,24,3030,250,16,1895,37,164,4357,55,3389,290,98,1233,1798,634,2505,263,94,2713,373,1527,267,199,145,1184,336,653
United Kingdom of Great Britain and Northern Ireland,4475,124,156,3192,130,27,1399,48,275,465,136,17,2450,130,20,1396,36,74,3444,72,2850,210,76,815,1387,378,2111,132,50,2149,212,1472,251,142,99,863,319,658
Canada,3012,53,117,2252,75,21,1115,46,188,361,58,14,1690,81,17,986,19,43,2355,27,1981,151,59,483,981,282,1360,152,52,1593,191,920,173,51,82,686,291,375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Saint Kitts and Nevis,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
Tuvalu,1,0,0,1,1,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,1,0,1,1,0,0,0,0,1,0,0
Papua New Guinea,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Brunei Darussalam,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Dominica,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,1,0,1,0,0,1,0,1,1,1,0,0,0,1

In [ ]:
country_Respondents = data['Country'].value_counts()
df = df.rename(columns={'Country': 'Respondents'})
for str in languages_Answers:
     pd.concat([df, grouped_Country['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains(str).sum())], axis = 'columns', sort = False)

In [ ]:
grouped_Country['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum()).loc['United States of America']

In [ ]:
1 - (data['MentalHealth'].isna().sum() + (data['MentalHealth'] == 'None of the above').sum()) /data.shape[0] # 1 out of 4 is not without health problems? that sounds like a lot
# sadly this question was not asked in any surveys pre Covid as far as I could see

In [ ]:
df = data.groupby(['YearsCode']).median()['ConvertedCompYearly']

In [ ]:
df.plot.bar() #how to sort the columns, why doenst it work the right way automatically?

In [ ]:
#gender/race pay gap present in developer industry? if so, did it get better over time (todo?)?
#do we have enough data?
data.shape[0]-data['ConvertedCompYearly'].isna().sum()
#46844 is enough
data['ConvertedCompYearly'].median()

In [ ]:
data['Gender'].value_counts() #Most answered binary, so the others are statiscally irrelevant.

In [ ]:
GenderSalary = data.groupby(['Gender', 'Country'])['ConvertedCompYearly']

In [ ]:
(GenderSalary.median()['Man']/GenderSalary.median()['Woman'])['United States of America'] - 1 #percentage of more income of men

In [ ]:
(GenderSalary.median()['Man']/GenderSalary.median()['Woman'])['Germany'] - 1

In [ ]:
top_ten=data['Country'].value_counts().nlargest(10)
((GenderSalary.median()['Man']/GenderSalary.median()['Woman'])-1)[top_ten.index] #top_ten = highest surveyed countries, for others the values become unusable
# is this represantive? what happend in poland?
# for germany the results are only 3% off, this site says 18% for 2020 https://www.destatis.de/DE/Themen/Arbeit/Arbeitsmarkt/Qualitaet-Arbeit/Dimension-1/gender-pay-gap.html

In [ ]:
((GenderSalary.median()['Man']/GenderSalary.median()['Woman'])-1)[top_ten.index].plot.bar()

In [ ]:
#lets do the same for race? (todo?)

In [ ]:
EdLevelSalary = data.groupby(['EdLevel'])['ConvertedCompYearly'].median().sort_values()

In [ ]:
EdLevelSalary.plot.bar()

In [ ]:
#check for missed values
#List of all the coloumns with missing values
data.isna().any()

In [ ]:
print('Number of columns with missing values:',len(data.columns[data.isnull().any()].to_list()))

In [ ]:
#Percentage of missing values
data.isnull().sum()/data.shape[0] *100

In [ ]:
#columns with more than 75% missing values
print(data.columns[data.isnull().mean()>0.75].to_list())
print('Number of columns with more the 75% missing values:',len(data.columns[data.isnull().mean()>0.75].to_list()))

In [ ]:
#Highest Surveyed Countries

top_ten=data['Country'].value_counts().nlargest(10)


plt.subplots(figsize=(12,4))
top_ten.plot.bar()
plt.xlabel('Country')
plt.ylabel('Count')
plt.show()

In [ ]:
# EDA on used programming languages in this survey

temp=data['LanguageHaveWorkedWith'].dropna() #clean data
print(temp)
language=[]
for i in temp:
    if isinstance(i, int):
        print('int value.. no need to split') #reason: I just could't get rid of that value! it's the last one so 'break' helped
        break
    x = i.split(";")
    language.append(x)
    
import itertools
languages=list(itertools.chain.from_iterable(language))
languages=list(set(languages)) #remove duplicated values
print(languages)

In [ ]:
#count users of the used languages

used_languages={} #cant we do that with pandas instead of dictionaries?
for i in languages:
    used_languages[i]=(data['LanguageHaveWorkedWith'].apply(lambda x: i in str(x).split(';')).value_counts()[1])
print(used_languages)
df_lan = pd.DataFrame({'Language' : used_languages.keys() , 'Users' : used_languages.values() })
#df_lan = df_lan.sort_values('Users').iloc[::-1] # sorting
#pd.DataFrame.from_dict(used_languages,orient='index',columns=['Users'])

In [ ]:
print(df_lan)

In [ ]:
# Proffession of surveyed users
proffession=data['MainBranch'].value_counts()
proffession.plot(kind='pie',figsize=(8,8),title='Main Branch')
plt.show()

In [ ]:
#let's have a look on coding experience ..
# but first, we should clean our data from non numeric values

data.loc[data['YearsCode'] =='Less than 1 year'] = 0
data.loc[data['YearsCode'] =='More than 50 years'] = 50
experience = data['YearsCode'].value_counts()
experience.plot()
#experience.sort_values()

In [ ]:
# separating male and female: 

male = data[data.Gender == 'Man']  
male.shape

In [ ]:
female = data[data.Gender == 'Woman']  #sex = 1 == male?
female.shape

In [ ]:
# now we can see median coding experience for both genders

male.YearsCode.median()

In [ ]:
female.YearsCode.median()